export const ERROR_HANDLER = 'ERROR_HANDLER';

export const INIT_PASSENGERS = 'INIT_PASSENGERS';

export const FETCH_PASSENGERS = 'FETCH_PASSENGERS';
export const PASSENGERS_SUCCESS = 'PASSENGERS_SUCCESS';
export const PASSENGERS_FAILD = 'PASSENGERS_FAILD';
